### ISSUE TITLE
Renew Plugin: Cannot subtract strings

### ISSUE THREAD

**Issue by pjf** [yanick/Taskwarrior-Kusarigama#14]
I've enabled `Renew` with `task-kusarigama add Renew`:

> kusarigama.plugins=GitCommit,Renew

This doesn't seem to enable the UDAs, so I've copied them from the blog:

```
uda.renew.type=string
uda.renew.label=Create a follow-up task upon closing
uda.rdue.type=string
uda.rdue.label=Next task due date
uda.rwait.type=string
uda.rwait.label=Next task wait period
```

And I'm now trying to use the [blog example](http://techblog.babyl.ca/entry/taskwarrior) of renew. Alas, it gives me an obscure error:

```
$ t add renew:1 rdue:now+1week rwait:due-3days Do Laundry
Cannot subtract strings
```

If I change the relevant UDAs to be dates, I get told that `'due-3days' is not a valid date in the 'Y-M-D' format.`

I suspect if I hack the strings directly into the task as UDAs they might work, but I've no idea how to do this from the command-line.

**Comment by yanick** [comment]
`due-3days` doesn't work because `task calc` doesn't recognize `due`. If you replace it by `rwait:now+4days`, it should work.

(and this is a good one, I should have the command do a `$rwait =~ s/due/$rdue/` for convenience)

And yeah, rdue and rwait are strings, not dates. They are only calculated as date via the magic of `task calc` as the previous task is done.

**Comment by yanick** [comment]
Okay, `task` does some munging under the hood:

```
⥼ task add project:due-b Do Laundry
Cannot subtract strings
```

**Comment by yanick** [comment]
https://bug.tasktools.org/browse/TW-1900

**Comment by yanick** [comment]
Will mark this as closed, as we're fudging our way around the tw issue. I've opened #21 to clean things up once the root bug is fixed.
